name: Deploy Eureka to Amazon EKS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1                  
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_EUREKA }} 
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER }}      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}
    - id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }} 
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
    - env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i "s|\\\${IMAGE_TAG}|$IMAGE_TAG|g" k8s/eureka.yml
        kubectl apply -f k8s/eureka.yml